import type { Metadata } from "next";
import { Manrope as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Provider from "@/provider/sessionProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// ******** you can change this metadata information with yours
export const metadata: Metadata = {
  title: "TN Next JS starter",
  description: "Generated by TechNerd",

  // ********** you can find the favicons in /public folder
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body
        className={cn(
          "min-h-screen bg-neutral-900 selection:bg-purple-500/40 selection:text-purple-200 text-neutral-500 font-sans antialiased",
          fontSans.variable
        )}
      >
        <Provider> {children}</Provider>
      </body>
    </html>
  );
}
